/// <reference types="react" />
export * from './Bag';
export * from './Block';
export * from './Calendar';
export * from './Cards';
export * from './Chart';
export * from './Checkbold';
export * from './Checkcircle';
export * from './ChevronDown';
export * from './ChevronLeft';
export * from './ChevronRight';
export * from './Circlemoney';
export * from './Circleplus';
export * from './Clock';
export * from './Close';
export * from './CloseFilled';
export * from './Comment';
export * from './Community';
export * from './Delete';
export * from './DollarSign';
export * from './Download';
export * from './Email';
export * from './Eye';
export * from './Eyeslash';
export * from './Filter';
export * from './Gear';
export * from './Gridview';
export * from './Heart';
export * from './Heartfilled';
export * from './Home';
export * from './HorizontalCircleDots';
export * from './Horizontaldots';
export * from './Image';
export * from './Info';
export * from './LeftArrow';
export * from './List';
export * from './Live';
export * from './Lock';
export * from './Media';
export * from './Message';
export * from './Messageblast';
export * from './Minus';
export * from './Money';
export * from './Morecircle';
export * from './Notification';
export * from './PaymentIcon';
export * from './PillSelected';
export * from './PillUnSelected';
export * from './PlayIcon';
export * from './Plus';
export * from './Rightarrow';
export * from './Rotate';
export * from './Search';
export * from './Send';
export * from './SliderArrow';
export * from './Subscriber';
export * from './Subscription';
export * from './Tableview';
export * from './Unlock';
export * from './User';
export * from './Verticaldots';
export * from './World';
export type IconType = 'Account' | 'Bag' | 'Block' | 'Calendar' | 'Cards' | 'Chart' | 'Checkbold' | 'Checkcircle' | 'ChevronDown' | 'ChevronLeft' | 'ChevronRight' | 'Circlemoney' | 'Circleplus' | 'Clock' | 'Close' | 'CloseFilled' | 'Comment' | 'Community' | 'Delete' | 'DollarSign' | 'Download' | 'Email' | 'Eye' | 'Eyeslash' | 'Filter' | 'Gear' | 'Heart' | 'Heartfilled' | 'Home' | 'HorizontalCircleDots' | 'Horizontaldots' | 'Image' | 'Info' | 'LeftArrow' | 'List' | 'Live' | 'Lock' | 'Media' | 'Message' | 'Messageblast' | 'Minus' | 'Money' | 'Morecircle' | 'Notification' | 'PaymentIcon' | 'PillSelected' | 'PillUnSelected' | 'PlayIcon' | 'Plus' | 'Rightarrow' | 'Rotate' | 'Search' | 'Send' | 'SliderArrow' | 'Subscriber' | 'Subscription' | 'Unlock' | 'User' | 'Verticaldots' | 'World' | 'Gridview' | 'Tableview';
export declare const Icon: React.FC<{
    name: IconType;
    size: string;
}>;
//# sourceMappingURL=index.d.ts.map